### PR TITLE
Merge twemoji 14.0.2

### PR DESCRIPTION
**Pull request by rinsuki**

### CODE REVIEW

**Comment by marcpinet** [comment]
@jdecked

**Comment by rinsuki** [comment]
jdecked is original twemoji author, I think correct ping destination is @birarda

**Comment by birarda** [comment]
Thanks, I've updated our master branch to rebase on Twitter's 14.0.2 changes and will publish the updated package.

I hope the master rebase doesn't cause you problems, that's historically how we've re-applied our changes here.

**Comment by marcpinet** [comment]
> Thanks, I've updated our master branch to rebase on Twitter's 14.0.2 changes and will publish the updated package.
> 
> I hope the master rebase doesn't cause you problems, that's historically how we've re-applied our changes here.

How much time will it take for the update to come live?

**Comment by birarda** [comment]
> How much time will it take for the update to come live?

If you mean on npm the 14.0.2 package is live now!

https://www.npmjs.com/package/@discordapp/twemoji/v/14.0.2

**Comment by marcpinet** [comment]
> > How much time will it take for the update to come live?
> 
> If you mean on npm the 14.0.2 package is live now!
> 
> https://www.npmjs.com/package/@discordapp/twemoji/v/14.0.2

Oh okay, I meant, when will we be able to use the new emojis in Discord now?

**Comment by birarda** [comment]
> > > How much time will it take for the update to come live?
> > 
> > 
> > If you mean on npm the 14.0.2 package is live now!
> > https://www.npmjs.com/package/@discordapp/twemoji/v/14.0.2
> 
> Oh okay, I meant, when will we be able to use the new emojis in Discord now?

That’s also dependent on a data source we use updating to 14, which they’ve told us won’t be until June or July. I’m planning on seeing if we can release these sooner without that but can’t make any promises there.

**Pull request closed without merging**
